### ISSUE TITLE
Pages broken in Spanish

### ISSUE THREAD

**Issue by srl295** [ibm-cloud-docs/language-translator#64]
Spanish is my default language.

https://cloud.ibm.com/docs/services/language-translator?topic=language-translator-customizing  or https://cloud.ibm.com/docs/services/language-translator?topic=language-translator-customizing&locale=es returns a broken page:

> No se ha encontrado la página
> Parece que no podemos encontrar lo que está buscando. Pruebe la búsqueda en los Documentos de IBM Cloud para encontrar información.

https://cloud.ibm.com/docs/services/language-translator?topic=language-translator-customizing&locale=en works if i set the lang to english.

**Comment by SirSpidey** [comment]
Fixed, but issue not updated.
