### ISSUE TITLE
Status: 401 Reason: Unauthorized

### ISSUE THREAD

**Issue by uttamraj9** [ibm-cloud-docs/language-translator#79]
I am using stream sets to stream tweets and convert text the pipeline is able to translate some tweets but some of the tweets are not getting translated using ibm translator.
error form streamsets:
HTTP_01 - Error fetching resource. Status: 401 Reason: Unauthorized org.glassfish.jersey.message.internal.EntityInputStream@2f72988a
 
<img width="1118" alt="Screen Shot 2019-11-21 at 5 35 36 PM" src="https://user-images.githubusercontent.com/7234899/69342654-71580900-0c85-11ea-9ed7-ac4e043b3977.png">
<img width="668" alt="Screen Shot 2019-11-21 at 5 36 02 PM" src="https://user-images.githubusercontent.com/7234899/69342655-71f09f80-0c85-11ea-8c17-774501f9649b.png">

**Comment by SirSpidey** [comment]
issue with code, not the docs. closing
