### ISSUE TITLE
{"error":"A document attachment is needed in multipart POST.","code":400}

### ISSUE THREAD

**Issue by burelamanohar** [ibm-cloud-docs/language-translator#81]
I am getting below error:
{"error":"A document attachment is needed in multipart POST.","code":400}

When I tried to POST txt or pdf files.  
curl -X POST  ^
--user "apikey:xxxxxxxxxxxxx"  ^
--form "file=xxxxxxxxxx.pdf"  ^
--form "model_id=96221b69-8e46-42e4-a3c1-808e17c787ca"  ^
"{url}/v3/documents?version=2018-05-01"

Please help me to resolve this issue. I tried passing header with multipart/text and got below error:
{"error":"Supplied content type is not supported.","code":415}

**Comment by SirSpidey** [comment]
Hi @burelamanohar 
I think you're just missing the prefix for the file. Use `@` to specify a file:
```sh
--form "file=@xxxxxxxxxx.pdf" ^
```

> To force the 'content' part to be a file, prefix the file name with an @ sign. To just get the content part from a file, prefix the file name with the symbol <. The difference between @ and < is then that @ makes a file get attached in the post as a file upload, while the < makes a text field and just get the contents for that text field from a file.
From https://curl.haxx.se/docs/manpage.html#-F

**Comment by burelamanohar** [comment]
Thank you so much @SirSpidey , it worked.
Appreciate your quick response. Have a good one :)
