### ISSUE TITLE
help with translation service

### ISSUE THREAD

**Issue by stacy734** [ibm-cloud-docs/language-translator#83]
Hello,
I'm a first time user with the IBM Cloud Translation Service.  I have an API key and URL from the Cloud Foundry interface.  I have curl installed on a Linux platform.

I am using this command (I have deleted part of the API key for security reasons).  

curl -X POST --user "apikey:{LW2D9D............OazLRhWIxpc0zICk}" --form "file=@test1.docx" --form "source=en" --form "target=fr" "{url}/https://api.us-south.language-translator.watson.cloud.ibm.com/instances/cd08d89a-9760-4666-90d2-397ba20aaa3d"

Produces this error:
curl: (1) Protocol url/https not supported or disabled in libcurl

I assume I have incorrectly formatted the command.  Any advice will be appreciated.

**Comment by SirSpidey** [comment]
Hi. You just need to remove the `{url}` placeholder and `/`. So `"https://api.us-south.language-translator.watson.cloud.ibm.com/instances/cd08d89a-9760-4666-90d2-397ba20aaa3d"`

**Comment by stacy734** [comment]
Thanks for your speedy response.

Different error now (API key partially removed)
curl -X POST --user "apikey:{LW2D9D............OazLRhWIxpc0zICk}" --form "file=@test1.docx" --form "source=en" --form "target=fr" "https://api.us-south.language-translator.watson.cloud.ibm.com/instances/cd08d89a-9760-4666-90d2-397ba20aaa3d"

<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;179&#46;3700c045&#46;1594070067&#46;4fd64125
</BODY></HTML>

**Comment by stacy734** [comment]
Oops, I see you closed this ticket.  I'll open a new one.
