### ISSUE TITLE
Error when using Translation Service

### ISSUE THREAD

**Issue by stacy734** [ibm-cloud-docs/language-translator#84]
Continued from Issue #83 

Different error now (API key partially removed)
curl -X POST --user "apikey:{LW2D9D............OazLRhWIxpc0zICk}" --form "file=@test1.docx" --form "source=en" --form "target=fr" "https://api.us-south.language-translator.watson.cloud.ibm.com/instances/cd08d89a-9760-4666-90d2-397ba20aaa3d"

<TITLE>Error</TITLE> An error occurred while processing your request.
Reference #179.3700c045.1594070067.4fd64125

**Comment by SirSpidey** [comment]
Hi @stacy734. It looks like you are trying to translate a document but not using the full endpoint for it (`/v3/documents`). 

Here it is on multiple lines for readability. Just update the URL in your request
```
curl -X POST --user apikey:{apikey}  \
--form "file=@test1.docx" \ 
--form "source=en" --form "target=fr"  \
"https://api.us-south.language-translator.watson.cloud.ibm.com/instances/cd08d89a-9760-4666-90d2-397ba20aaa3d/v3/documents?version=2018-05-01"
```

Take a look at https://cloud.ibm.com/apidocs/language-translator#translate-document
