### ISSUE TITLE
Which language code standard we are following? ISO 2 ? ISO 3

### ISSUE THREAD

**Issue by lukasonokoleg** [ibm-cloud-docs/language-translator#87]
Hello, 

I've been looking into list of supported languages - and I've missed mention of which standard of language codes are supported? 

ISO 2? ISO 3? 

ISO 2 - when we code language with 2 chars, 
ISO 3 - when we code language with 3 chars. 

Can this be added? 

In case if more questions - please reach me on slack or IBM email oleg.lukasonok@lt.ibm.com

**Comment by miltatibm** [comment]
@SirSpidey can you take a look a this please?

**Comment by jeffpk62** [comment]
@lukasonokoleg If you're referring to the language codes we use to identify languages in LT, it appears that we use two-char ISO codes in all but one case, Montenegrin, in which case we use three chars (`cnr`).  Does that answer your question?

**Comment by lukasonokoleg** [comment]
@jeffpk62 - Question is - can this be documented on service docs? That all languages are coded with ISO-2 standard + exceptions?

**Comment by jeffpk62** [comment]
@lukasonokoleg I can open an issue to add a note to that effect in sections in which the country codes are listed.  For a variety of reasons, I can't predict when this will be added, but will try to stuff it in very soon before it becomes lost in the flood.

**Comment by jeffpk62** [comment]
@lukasonokoleg Please take a look at these two sections.  I've added the information to the text that precedes the tables of language codes.

- https://cloud.ibm.com/docs/language-translator?topic=language-translator-translation-models#list-languages-supported
- https://cloud.ibm.com/docs/language-translator?topic=language-translator-identifiable-languages#list-languages-identifiable

**Comment by jeffpk62** [comment]
@lukasonokoleg I am going to close this issue because I think Ive addressed your comments.  If you would like to see something different or additional, please just comment here.  Thanks again for the feedback!
